export const globalText = {
	finalPageContent: {
		title: 'Last Step - Congrats',
		subTitle: 'Add your items to cart and head to your store to pick out your new fish friend.',
		subTitle2: 'Hero Banner',
		bannerTitle: `Congrats,`,
		bannerTitle2: `you've build your tank!`,
		bannerSubTitle:
			'Add your items to cart & select in-store pickup. Your tank & new fish selections will be waiting! ',
		fishCare1: 'Test your water regularly',
		fishCare2: 'Remember to “cycle” your aquarium',
		fishCare3: 'Rinse off décor before placing in tank',
		fishCare4: 'Don’t add bacteria starter until you start adding fish',
	},
	headerTitle: 'Try Same-Day Delivery for FREE powered by DoorDash®! learn more >',
	readMore: 'Read more',
	featuredArticles: 'Featured articles',
	viewAll: 'View all',
	buildYourTank: 'BUILD YOUR TANK',
	buildYourTankMain: 'Build your tank',
	getStarted: 'get started',
	banner: 'Banner',
	bannerTitle: 'How to setup an aquarium',
	edit: 'Edit',
	noProductText: 'No Product Selected',
	bannerDescription:
		'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna.',
	subTotal: 'Subtotal',
	fishTitles: {
		title: 'Select your favorite fish',
		subTitle: 'Please select a fish you plan on building a tank for.',
	},
	allTankTitle: {
		title: `Select a tank`,
		subTitle: 'Choose from a small, medium, or large tank.',
	},
	accessoriesTitles: {
		title: 'Recommended accessories',
		subTitle: 'Add accessory item(s) to your tank.',
	},
	gravelDecorTitles: {
		title: 'Recommended gravel & decor',
		subTitle: 'Add gravel & decor item(s) to your tank.',
	},
	careTitles: {
		title: 'Recommended care for your tank',
		subTitle: 'Add care item(s) to your tank.',
	},
	dosDontsTitles: {
		title: 'Do’s and don’ts with your new fish',
		subTitle: '',
	},
	by: 'By',
	item: 'Item',
	goBack: 'Go back',
	continue: 'Continue',
	small: 'Small',
	medium: 'Medium',
	large: 'Large',
	addToCart: 'Add to cart',
};
